version: '3.3'
services:
  automl:
    build: .
    restart: "no"
    volumes:
    - ./:/opt/automl/
    - ../../datasets:/opt/automl/datasets
    - ../../../alexautoml:/opt/automl/alexautoml
    working_dir: /opt/automl/
    command: python3 -u ./model.py